//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace duo.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysKeyValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysKeyValue()
        {
            this.sysOrganStruct = new HashSet<sysOrganStruct>();
        }
    
        public int KID { get; set; }
        public int ParentID { get; set; }
        public int KType { get; set; }
        public string KName { get; set; }
        public string KValue { get; set; }
        public string KRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysOrganStruct> sysOrganStruct { get; set; }
    }
}
