//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace duo.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysRole()
        {
            this.sysPermissList = new HashSet<sysPermissList>();
            this.sysUserInfo_Role = new HashSet<sysUserInfo_Role>();
        }
    
        public int rID { get; set; }
        public Nullable<int> eDepID { get; set; }
        public int RoleType { get; set; }
        public string rName { get; set; }
        public string rRemark { get; set; }
        public int rSort { get; set; }
        public int rStatus { get; set; }
        public int rCreateID { get; set; }
        public System.DateTime rCreateTime { get; set; }
        public Nullable<int> rUpdateID { get; set; }
        public Nullable<System.DateTime> rUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysPermissList> sysPermissList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysUserInfo_Role> sysUserInfo_Role { get; set; }
    }
}
