//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace duo.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysUserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysUserInfo()
        {
            this.sysUserInfo_Role = new HashSet<sysUserInfo_Role>();
        }
    
        public int uID { get; set; }
        public string uLoginName { get; set; }
        public string uLoginPWD { get; set; }
        public string uRealName { get; set; }
        public string uTelphone { get; set; }
        public string uMobile { get; set; }
        public string uEmail { get; set; }
        public string uQQ { get; set; }
        public int uGender { get; set; }
        public int uStatus { get; set; }
        public int uCompanyID { get; set; }
        public Nullable<int> uDepID { get; set; }
        public Nullable<int> uWorkGroup { get; set; }
        public string uRemark { get; set; }
        public int uCreateID { get; set; }
        public System.DateTime uCreateTime { get; set; }
        public Nullable<int> uUpdateID { get; set; }
        public System.DateTime uUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysUserInfo_Role> sysUserInfo_Role { get; set; }
    }
}
