//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace duo.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wfWorkBranch
    {
        public int wfbID { get; set; }
        public int wfnID { get; set; }
        public string wfnToken { get; set; }
        public int wfNodeID { get; set; }
        public int fCreateID { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public Nullable<int> fUpdateID { get; set; }
        public Nullable<System.DateTime> fUpdateTime { get; set; }
    
        public virtual wfWorkNodes wfWorkNodes { get; set; }
    }
}
