//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace duo.CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wfWorkNodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wfWorkNodes()
        {
            this.wfProcess = new HashSet<wfProcess>();
            this.wfWorkBranch = new HashSet<wfWorkBranch>();
        }
    
        public int wfnID { get; set; }
        public int wfID { get; set; }
        public int wfnOrderNo { get; set; }
        public int wfNodeType { get; set; }
        public string wfNodeTitle { get; set; }
        public string wfnBizMethod { get; set; }
        public decimal wfnMaxNum { get; set; }
        public int wfnRoleType { get; set; }
        public Nullable<int> wfnExt1 { get; set; }
        public string wfnExt2 { get; set; }
        public int fCreateID { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public Nullable<int> fUpdateID { get; set; }
        public Nullable<System.DateTime> fUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wfProcess> wfProcess { get; set; }
        public virtual wfWork wfWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wfWorkBranch> wfWorkBranch { get; set; }
    }
}
