//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace duo.CRM.Services
{
    using System;
    using System.Collections.Generic;

    using Model;
    using IServices;
    using IRepository;
    using Common;
    public partial class sysPermissListServices : BaseServices<sysPermissList>, IsysPermissListServices
    {
        public IsysPermissListRepository _dal;
        #region 定义构造函数，接受antuofac将仓储层的具体实现类的对象注入到此类中
        public sysPermissListServices(IsysPermissListRepository dal)
        {
            this._dal = dal;
            base._baseDal = dal;
        }
        #endregion

        #region 业务逻辑
        /// <summary>
        /// 将用户权限按钮进行缓存操作
        /// </summary>
        /// <param name="uid"></param>
        /// <returns></returns>
        public List<Usp_GetFunctionsForUsers_Result> GetFunctionsForUserByCache(int uid)
        {
            //缓存key一定是每个用户有一个，不重复
            string cacheKey = Keys.PermissFunctionsForUser + uid;
            //1.0根据用户获取其权限按钮数据
            object data = Common.CacheMgr.GetData<List<Usp_GetFunctionsForUsers_Result>>(cacheKey);
            if (data == null)
            {
                //从数据库获取一份权限按钮数据
                var plist = _baseDal.RunProc<Usp_GetFunctionsForUsers_Result>("Usp_GetFunctionsForUsers " + uid);
                //将数据加入缓存
                CacheMgr.SetData(cacheKey, plist);
                data = plist;
            }

            return data as List<Usp_GetFunctionsForUsers_Result>;

        }
        #endregion
    }
}
